services:
  postgres:
    image: postgres:15
    container_name: olist_postgres
    environment:
      POSTGRES_USER: olist_user
      POSTGRES_PASSWORD: olist_pass
      POSTGRES_DB: olist_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: olist_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: h2
    depends_on:
      - postgres

  prefect:
    image: prefecthq/prefect:2-python3.11
    container_name: olist_prefect
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    environment:
      PREFECT_UI_URL: http://localhost:4200
      PREFECT_API_URL: http://localhost:4200/api

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    container_name: olist_pipeline
    depends_on:
      - postgres
      - prefect
    environment:
      PREFECT_API_URL: http://olist_prefect:4200/api

volumes:
  postgres_data: