FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install prefect==2.14.21 griffe==0.38.1

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

ENV PREFECT_API_URL=http://olist_prefect:4200/api

CMD ["python", "orchestration/flow.py"]