services:
  postgres:
    image: postgres:15
    container_name: olist_postgres
    environment:
      POSTGRES_USER: olist_user
      POSTGRES_PASSWORD: olist_pass
      POSTGRES_DB: olist_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: olist_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: h2
    depends_on:
      - postgres

volumes:
  postgres_data: